build:
  stage: build
  script:
    - mkdir build
    - cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT -DCMAKE_C_COMPILER=/usr/lib/ccache/clang-8 -DCMAKE_CXX_COMPILER=/usr/lib/ccache/clang++-8
    - ninja -C build
  artifacts:
    paths:
      - mybinary
  # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
  # cache:
  #   paths:
  #     - "*.o"

test:
  stage: test
  script:
    - ./runmytests.sh
