language: cpp

sudo: false

matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - ninja-build
      env:
        - MATRIX_EVAL="Coverage='On' && CXX='g++-7' && TYPE='Debug'"
      install:
        - eval "${MATRIX_EVAL}"
        - pip install --user cpp-coveralls
        - bash ./tools/travis/linux_deps.sh
        - $HOME/binary_root/bin/cmake . -DCMAKE_BUILD_TYPE=Debug -DOPENBVE2_ON_TRAVIS=True -DOPENBVE2_CODE_COVERAGE=On -GNinja
      after_success:
        - coveralls --gcov gcov-7 -e dependencies -e libparsers/tests -e test_main -E '.*?CMakeFiles.*?' -E '.*?cotire.*?'

    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - ninja-build
      env:
        - MATRIX_EVAL="LINKER='LD' && CXX=g++-7 && TYPE='RelWithDebInfo'"
      install:
        - eval "${MATRIX_EVAL}"
        - bash ./tools/travis/linux_deps.sh
        - mkdir -p build
        - cd build && $HOME/binary_root/bin/cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DOPENBVE2_ON_TRAVIS=True -GNinja

    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - ninja-build
      env:
        - MATRIX_EVAL="LINKER='LD' && CXX=g++-7 && TYPE='Release'"
      install:
        - eval "${MATRIX_EVAL}"
        - bash ./tools/travis/linux_deps.sh
        - mkdir -p build
        - cd build && $HOME/binary_root/bin/cmake .. -DCMAKE_BUILD_TYPE=Release -DOPENBVE2_ON_TRAVIS=True -GNinja
          
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - ninja-build
            - libstdc++-5-dev
            - clang-6.0
      env:
        - MATRIX_EVAL="SANITIZE='Asan,UBsan' && CXX=clang++-6.0 && TYPE='Debug'"
      install:
        - eval "${MATRIX_EVAL}"
        - bash ./tools/travis/linux_deps.sh
        - mkdir -p build
        - cd build && UBSAN_OPTIONS=print_stacktrace=1 $HOME/binary_root/bin/cmake .. -DCMAKE_BUILD_TYPE=Debug -DOPENBVE2_ON_TRAVIS=True -DSANITIZE_ADDRESS=On -DSANITIZE_UNDEFINED=On -GNinja

    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - ninja-build
            - libstdc++-5-dev
            - clang-6.0
      env:
        - MATRIX_EVAL="SANITIZE='Tsan' && CXX=clang++-6.0 && TYPE='Debug'"
      install:
        - eval "${MATRIX_EVAL}"
        - bash ./tools/travis/linux_deps.sh
        - mkdir -p build
        - cd build && $HOME/binary_root/bin/cmake .. -DCMAKE_BUILD_TYPE=Debug -DOPENBVE2_ON_TRAVIS=True -DSANITIZE_Thread=On -GNinja
          
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - ninja-build
            - libstdc++-5-dev
            - clang-6.0
            - lld-6.0
      env:
        - MATRIX_EVAL="LINKER='LLD' && CXX=clang++-6.0 && TYPE='Debug'"
      install:
        - eval "${MATRIX_EVAL}"
        - bash ./tools/travis/linux_deps.sh
        - mkdir -p build
        - cd build && $HOME/binary_root/bin/cmake .. -DCMAKE_BUILD_TYPE=Debug -DOPENBVE2_ON_TRAVIS=True -DCMAKE_EXE_LINKER_FLAGS='-fuse-ld=lld' -DCMAKE_SHARED_LINKER_FLAGS='-fuse-ld=lld' -GNinja

    - os: osx
      osx_image: xcode9.2
      install:
        - brew update
        - HOMEBREW_NO_AUTO_UPDATE=1 brew upgrade cmake
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install ninja
        - bash ./build-deps-unix.sh
        - mkdir -p build
        - cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DOPENBVE2_ON_TRAVIS=True -GNinja

before_install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/Deps"
  - mkdir ${DEPS_DIR}

  # Download GCC 7.1
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      GCC_URL="https://bsfproxy.connorwfitzgerald.com/gcc-7.1-trusty.zip"
      cd ${DEPS_DIR}
      mkdir gcc
      cd gcc
      wget --no-check-certificate --quiet - ${GCC_URL}
      unzip -q gcc-7.1-trusty.zip
      export PATH=${DEPS_DIR}/gcc/bin:$PATH
      export LD_LIBRARY_PATH=${DEPS_DIR}/gcc/lib:$LD_LIBRARY_PATH
      export LD_LIBRARY_PATH=${DEPS_DIR}/gcc/lib64:$LD_LIBRARY_PATH
    fi

  # Download binutils 2.28
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      BINUTILS_URL="https://bsfproxy.connorwfitzgerald.com/binutils-2.28-trusty.zip"
      cd ${DEPS_DIR}
      mkdir binutils
      cd binutils
      wget --no-check-certificate --quiet - ${BINUTILS_URL}
      unzip -q binutils-2.28-trusty.zip
      export PATH=${DEPS_DIR}/binutils/bin:${PATH}
      export LD_LIBRARY_PATH=${DEPS_DIR}/binutils/lib:$LD_LIBRARY_PATH
    fi

  - cd ${TRAVIS_BUILD_DIR}

script:
  - ninja
  - bin/test_main
