language: cpp

sudo: true

matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - ninja-build
            - gcc-7
            - g++-7
      env:
        - MATRIX_EVAL="CC='gcc-7' && CXX='g++-7' && TYPE='Debug' && Coverage='On'"
      before_install:
        - eval "${MATRIX_EVAL}"
        - pip install --user cpp-coveralls
      # Get Newer CMake
        - wget https://cmake.org/files/v3.10/cmake-3.10.1-Linux-x86_64.sh
        - mkdir $HOME/cmake_root
        - bash cmake-3.10.1-Linux-x86_64.sh --skip-license --prefix=$HOME/cmake_root --exclude-subdir
        - $HOME/cmake_root/bin/cmake --version
        - bash ./build-deps-unix.sh
        - $HOME/cmake_root/bin/cmake . -DCMAKE_BUILD_TYPE=$TYPE -DOPENBVE2_ON_TRAVIS=True -DOPENBVE2_CODE_COVERAGE=$COVERAGE -GNinja
      after_success:
        - coveralls --gcov gcov-7 -e dependencies -e libparsers/tests -e test_main -E '.*?CMakeFiles.*?' -E '.*?cotire.*?'

    - os: linux
      dist: precise
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - ninja-build
            - gcc-5
            - g++-5
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
      before_install:
        - eval "${MATRIX_EVAL}"
      # Get Newer CMake
        - wget https://cmake.org/files/v3.10/cmake-3.10.1-Linux-x86_64.sh
        - sudo bash cmake-3.10.1-Linux-x86_64.sh --skip-license --prefix=/usr/local --exclude-subdir
        - cmake --version
      # Build Boost.... 
        - bash ./build-deps-unix.sh
      # Do rest of stuff
        - mkdir build
        - cd build && cmake .. -DOPENBVE2_ON_TRAVIS=True -GNinja

    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - ninja-build
            - gcc-7
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      before_install:
        - eval "${MATRIX_EVAL}"
      # Get Newer CMake
        - wget https://cmake.org/files/v3.10/cmake-3.10.1-Linux-x86_64.sh
        - sudo bash cmake-3.10.1-Linux-x86_64.sh --skip-license --prefix=/usr/local --exclude-subdir
        - cmake --version
      # Build Boost.... 
        - bash ./build-deps-unix.sh
      # Do rest of stuff
        - mkdir build
        - cd build && cmake .. -DOPENBVE2_ON_TRAVIS=True -GNinja


    - os: linux
      dist: precise
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - ninja-build
            - libstdc++-5-dev
            - clang-3.6
      env:
        - MATRIX_EVAL="CC=clang-3.6 && CXX=clang++-3.6"
      before_install:
        - eval "${MATRIX_EVAL}"
      # Get Newer CMake
        - wget https://cmake.org/files/v3.10/cmake-3.10.1-Linux-x86_64.sh
        - sudo bash cmake-3.10.1-Linux-x86_64.sh --skip-license --prefix=/usr/local --exclude-subdir
        - cmake --version
      # Build Boost.... 
        - bash ./build-deps-unix.sh
      # Do rest of stuff
        - mkdir build
        - cd build && cmake .. -DOPENBVE2_ON_TRAVIS=True -GNinja
          
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - ninja-build
            - libstdc++-5-dev
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
      before_install:
        - eval "${MATRIX_EVAL}"
      # Get Newer CMake
        - wget https://cmake.org/files/v3.10/cmake-3.10.1-Linux-x86_64.sh
        - sudo bash cmake-3.10.1-Linux-x86_64.sh --skip-license --prefix=/usr/local --exclude-subdir
        - cmake --version
      # Build Boost.... 
        - bash ./build-deps-unix.sh
      # Do rest of stuff
        - mkdir build
        - cd build && cmake .. -DOPENBVE2_ON_TRAVIS=True -GNinja

    - os: osx
      osx_image: xcode6.4
      before_install:
        - brew update
        - HOMEBREW_NO_AUTO_UPDATE=1 brew upgrade cmake
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install ninja
      # Build Boost.... 
        - bash ./build-deps-unix.sh
      # Do rest of stuff
        - mkdir build
        - cd build && cmake .. -DOPENBVE2_ON_TRAVIS=True -GNinja

    - os: osx
      osx_image: xcode9.2
      before_install:
        - brew update
        - HOMEBREW_NO_AUTO_UPDATE=1 brew upgrade cmake
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install ninja
      # Build Boost.... 
        - bash ./build-deps-unix.sh
      # Do rest of Stuff
        - mkdir build
        - cd build && cmake .. -DOPENBVE2_ON_TRAVIS=True -GNinja

script:
  - ninja
  - bin/test_parsers
