language: cpp

sudo: true

matrix:
  include:
    - os: linux
      dist: precise
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - ninja-build
            - gcc-5
            - g++-5
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
      before_install:
        - eval "${MATRIX_EVAL}"
      # Get Newer CMake
        - wget https://cmake.org/files/v3.10/cmake-3.10.1-Linux-x86_64.sh
        - sudo bash cmake-3.10.1-Linux-x86_64.sh --skip-license --prefix=/usr/local --exclude-subdir
        - cmake --version
      # Build Boost.... 
        - bash ./build-deps-unix.sh
      # Do rest of stuff
        - mkdir build
        - cd build && cmake .. -DOPENBVE2_ON_TRAVIS=True -GNinja

    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - ninja-build
            - gcc-6
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
      # Get Newer CMake
        - wget https://cmake.org/files/v3.10/cmake-3.10.1-Linux-x86_64.sh
        - sudo bash cmake-3.10.1-Linux-x86_64.sh --skip-license --prefix=/usr/local --exclude-subdir
        - cmake --version
      # Build Boost.... 
        - bash ./build-deps-unix.sh
      # Do rest of stuff
        - mkdir build
        - cd build && cmake .. -DOPENBVE2_ON_TRAVIS=True -GNinja


    - os: linux
      dist: precise
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - ninja-build
            - libstdc++-5-dev
            - clang-3.6
      env:
        - MATRIX_EVAL="CC=clang-3.6 && CXX=clang++-3.6"
      before_install:
        - eval "${MATRIX_EVAL}"
      # Get Newer CMake
        - wget https://cmake.org/files/v3.10/cmake-3.10.1-Linux-x86_64.sh
        - sudo bash cmake-3.10.1-Linux-x86_64.sh --skip-license --prefix=/usr/local --exclude-subdir
        - cmake --version
      # Build Boost.... 
        - bash ./build-deps-unix.sh
      # Do rest of stuff
        - mkdir build
        - cd build && cmake .. -DOPENBVE2_ON_TRAVIS=True -GNinja
          
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - ninja-build
            - libstdc++-5-dev
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
      before_install:
        - eval "${MATRIX_EVAL}"
      # Get Newer CMake
        - wget https://cmake.org/files/v3.10/cmake-3.10.1-Linux-x86_64.sh
        - sudo bash cmake-3.10.1-Linux-x86_64.sh --skip-license --prefix=/usr/local --exclude-subdir
        - cmake --version
      # Build Boost.... 
        - bash ./build-deps-unix.sh
      # Do rest of stuff
        - mkdir build
        - cd build && cmake .. -DOPENBVE2_ON_TRAVIS=True -GNinja

    - os: osx
      osx_image: xcode6.4
      before_install:
        - brew update
        - brew upgrade cmake
        - brew install ninja
      # Build Boost.... 
        - bash ./build-deps-unix.sh
      # Do rest of stuff
        - mkdir build
        - cd build && cmake .. -DOPENBVE2_ON_TRAVIS=True -GNinja

    - os: osx
      osx_image: xcode9.2
      before_install:
        - brew update
        - brew upgrade cmake
        - brew install ninja
      # Build Boost.... 
        - bash ./build-deps-unix.sh
      # Do rest of Stuff
        - mkdir build
        - cd build && cmake .. -DOPENBVE2_ON_TRAVIS=True -GNinja

script:
  - ninja
