language: cpp

sudo: true

matrix:
  include:
    - os: linux
      dist: precise
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
          packages:
            - ninja-build
            - libboost-dev
            - gcc-5
            - g++-5
            - cmake-data
            - cmake
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - ninja-build
            - libboost-dev
            - gcc-6
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"


    - os: linux
      dist: precise
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - ninja-build
            - libboost-dev
            - clang-3.6
            - cmake-data
            - cmake
      env:
        - MATRIX_EVAL="CC=clang-3.6 && CXX=clang++-3.6"
          
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - ninja-build
            - libboost-dev
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

before_install:
  - eval "${MATRIX_EVAL}"
  - wget https://cmake.org/files/v3.10/cmake-3.10.1-Linux-x86_64.sh
  - sudo bash cmake-3.10.1-Linux-x86_64.sh
  - mkdir build
  - cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DOPENBVE2_ON_TRAVIS=True -GNinja
script:
  - ninja
