version: '0.0.0-{build}'

image: Visual Studio 2017

platform:
  - x64

clone_folder: c:\projects\bve-reborn
clone_depth: 1
skip_tags: true

init:
  - cmd: cmake --version
  - cmd: msbuild /version
 
configuration:
  - Release

install:
  - cmd: git submodule update --init --recursive

before_build:
  - cmd: cd C:\projects\bve-reborn
  - cmd: md build
  - cmd: cd build
  - cmd: cmake .. -G "Visual Studio 15 2017 Win64"

build:
  project: C:\projects\bve-reborn\build\BVE-Reborn.sln

test_script:
  - cmd: C:\projects\bve-reborn\build\bin\%CONFIGURATION%\tests.exe
