version: '0.0.0-{build}'

image: Visual Studio 2017

platform:
  - Win32
  - x64

environment:
  BOOST_ROOT: C:\Libraries\boost_1_64_0

clone_folder: c:\projects\openbve2
clone_depth: 1
skip_tags: true

init:
  - cmd: cmake --version
  - cmd: msbuild /version
 
configuration:
  - Release

install:
  - cmd: git submodule update --init --recursive

before_build:
  - cmd: cd C:\projects\openbve2
  - cmd: md build
  - cmd: cd build
  - cmd: if "%platform%"=="Win32" cmake .. -G "Visual Studio 15 2017" -DOPENBVE2_ON_TRAVIS=On -DBOOST_ROOT="%BOOST_ROOT%"
  - cmd: if "%platform%"=="x64" cmake .. -G "Visual Studio 15 2017 Win64" -DOPENBVE2_ON_TRAVIS=On -DBOOST_ROOT="%BOOST_ROOT%"

build:
  project: C:\projects\openbve2\build\openbve2.sln

test_script:
  - cmd: C:\projects\openbve2\build\bin\%CONFIGURATION%\test_main.exe
