if(WIN32)
    set(BVEREBORN_WIN 1)
elseif (APPLE)
    set(BVEREBORN_MAC 1)
elseif(UNIX AND NOT APPLE)
    set(BVEREBORN_LINUX 1)
else()
    message(FATAL_ERROR "Unsupported Platform")
endif()

if (NOT (CMAKE_SIZEOF_VOID_P STREQUAL "8"))
	message(FATAL_ERROR "BVE-Reborn is 64 bit only.")
endif()
