%include <glm/ivec2.i>
%include <glm/ivec3.i>
%include <glm/u8vec1.i>
%include <glm/u8vec2.i>
%include <glm/u8vec3.i>
%include <glm/u8vec4.i>
%include <glm/vec2.i>
%include <glm/vec3.i>
%include <glm/vec4.i>
