version: '0.0.0-{build}'

image: Visual Studio 2017

platform:
  - x64

clone_folder: c:\projects\bve-reborn
skip_tags: true

environment:
  VULKAN_SDK: C:\VulkanSDK\1.1.97.0
  VCPKG_ROOT: C:\Tools\vcpkg
  PATH: c:\projects\bve-reborn\;$(PATH)

init:
  - cmd: cmake --version
  - cmd: msbuild /version
 
configuration:
  - Release

install:
  - cmd: git submodule update --init --recursive
  - cmd: curl --silent --show-error --output VulkanSDK.exe https://cwfitz.com/s/19028-082433-VulkanSDK-1.1.97.0-Installer.exe
  - cmd: .\VulkanSDK.exe /S
  - cmd: curl --silent --show-error --output ispc.exe https://cwfitz.com/s/19079-081337-ispc.exe
  - cmd: C:\Python37-x64\python.exe ./build.py

before_build:
  - cmd: cd C:\projects\bve-reborn
  - cmd: md build
  - cmd: cd build
  - cmd: cmake .. -G "Visual Studio 15 2017 Win64" -Thost=x64 -DCMAKE_TOOLCHAIN_FILE=build-vcpkg/scripts/buildsystems/vcpkg.cmake

build:
  project: C:\projects\bve-reborn\build\BVE-Reborn.sln
  verbosity: minimal

after_build:
  - ps: rm -r build-vcpkg/buildtrees

cache:
  - build-vcpkg -> tools/ci/appveyor.yaml, build.py, .build-py

test_script:
  - cmd: C:\projects\bve-reborn\build\bin\%CONFIGURATION%\test-runner.exe
