version: '0.0.0-{build}'

image: Visual Studio 2017

platform:
  - x64

clone_folder: c:\projects\bve-reborn
skip_tags: true

environment:
  VULKAN_SDK: C:\VulkanSDK\1.1.97.0
  VCPKG_ROOT: C:\Tools\vcpkg
  PATH: c:\projects\bve-reborn\;$(PATH)

init:
  - cmd: cmake --version
  - cmd: msbuild /version
 
configuration:
  - Release

install:
  - cmd: git submodule update --init --recursive
  - cmd: curl --silent --show-error --output VulkanSDK.exe https://cwfitz.com/s/19028-082433-VulkanSDK-1.1.97.0-Installer.exe
  - cmd: .\VulkanSDK.exe /S
  - cmd: curl --silent --show-error --output ispc.exe https://cwfitz.com/s/19079-081337-ispc.exe
  - cmd: cd C:\Tools\vcpkg
  - cmd: git pull --ff -q
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - cmd: C:\Python37-x64\python.exe ./tools/vcpkg/setup.py --vcpkg-dir=c:/tools/vcpkg

before_build:
  - cmd: cd C:\projects\bve-reborn
  - cmd: md build
  - cmd: cd build
  - cmd: cmake .. -G "Visual Studio 15 2017 Win64" -Thost=x64 -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake

build:
  project: C:\projects\bve-reborn\build\BVE-Reborn.sln
  verbosity: minimal

cache: 
  - c:\tools\vcpkg\installed\
  - c:\tools\vcpkg\packages\

test_script:
  - cmd: C:\projects\bve-reborn\build\bin\%CONFIGURATION%\tests.exe

on_success:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 success $env:WEBHOOK_URL
on_failure:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 failure $env:WEBHOOK_URL
