stages:
  - build
  - test
  # - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
  stage: build
  script:
    - mkdir build
    - cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake -DCMAKE_C_COMPILER=/usr/lib/ccache/clang-8 -DCMAKE_CXX_COMPILER=/usr/lib/ccache/clang++-8 -DCMAKE_BUILD_TYPE=Debug -GNinja
    - ninja -C build
  artifacts:
    paths:
      - build/bin
  # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
  # cache:
  #   paths:
  #     - "*.o"

test:
  stage: test
  script:
    - ./build/bin/test-runner
